# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ad_query.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(524, 541)
        Form.setMinimumSize(QtCore.QSize(524, 541))
        Form.setMaximumSize(QtCore.QSize(524, 541))
        Form.setStyleSheet("")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 521, 541))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"border:1px solid rgb(217, 217, 217);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.btn_check = QtWidgets.QPushButton(self.groupBox)
        self.btn_check.setGeometry(QtCore.QRect(200, 500, 93, 28))
        self.btn_check.setStyleSheet("background-color: rgb(194, 170, 255,200);\n"
"")
        self.btn_check.setObjectName("btn_check")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(120, 30, 281, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 70, 341, 23))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_id.setStyleSheet("background-color: rgb(255, 255, 255,120);")
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.horizontalLayout.addWidget(self.lineEdit_id)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(10, 110, 501, 381))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255,60);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label.setBuddy(self.lineEdit_id)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_id, self.tableWidget)
        Form.setTabOrder(self.tableWidget, self.btn_check)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "管理员信息查询"))
        self.btn_check.setText(_translate("Form", "查询"))
        self.label_11.setText(_translate("Form", "请输入您想要查询管理员的账号"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"right\">账 号：</p></body></html>"))
        self.lineEdit_id.setPlaceholderText(_translate("Form", "请输入10位英文和数字结合的账号"))
