# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceRecord.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(836, 599)
        Form.setMinimumSize(QtCore.QSize(836, 599))
        Form.setMaximumSize(QtCore.QSize(836, 599))
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 841, 601))
        self.frame.setStyleSheet("QFrame {\n"
"border-image:url(:/lay/image/login1.png);\n"
"}\n"
"QLabel {\n"
"border-image:url();\n"
"}\n"
"QPushButton {\n"
"border-image:url();\n"
"}\n"
"QCheckBox {\n"
"border-image:url();\n"
"}\n"
"QTextEdit  {\n"
"border-image:url();\n"
"}\n"
"QLCDNumber  {\n"
"border-image:url();\n"
"}\n"
"QTableWidget  {\n"
"border-image:url();\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 201, 581))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("color: rgb(207, 207, 207);")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 30, 181, 131))
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_Init_mysql = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_Init_mysql.setGeometry(QtCore.QRect(10, 90, 161, 28))
        self.btn_Init_mysql.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.btn_Init_mysql.setObjectName("btn_Init_mysql")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 161, 16))
        self.label_3.setObjectName("label_3")
        self.lcd_save = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcd_save.setGeometry(QtCore.QRect(40, 50, 101, 31))
        self.lcd_save.setObjectName("lcd_save")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 170, 181, 181))
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget.setGeometry(QtCore.QRect(0, 20, 181, 111))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255,60);\n"
"color: rgb(0, 0, 0);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btn_sync_mysql = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_sync_mysql.setEnabled(False)
        self.btn_sync_mysql.setGeometry(QtCore.QRect(10, 140, 161, 28))
        self.btn_sync_mysql.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.btn_sync_mysql.setObjectName("btn_sync_mysql")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(9, 359, 181, 211))
        self.groupBox_5.setObjectName("groupBox_5")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setGeometry(QtCore.QRect(0, 20, 181, 191))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255,60);\n"
"color: rgb(0, 0, 0);")
        self.textEdit.setObjectName("textEdit")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(220, 10, 611, 581))
        self.groupBox.setAccessibleDescription("")
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setStyleSheet("color: rgb(207, 207, 207);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.face_label = QtWidgets.QLabel(self.groupBox)
        self.face_label.setGeometry(QtCore.QRect(10, 60, 591, 471))
        self.face_label.setStyleSheet("\n"
"border:1px solid black\n"
"")
        self.face_label.setObjectName("face_label")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 21, 591, 32))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_external = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_external.setObjectName("checkBox_external")
        self.horizontalLayout.addWidget(self.checkBox_external)
        self.btn_open_camera = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_open_camera.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.btn_open_camera.setObjectName("btn_open_camera")
        self.horizontalLayout.addWidget(self.btn_open_camera)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.btn_start_check = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_start_check.setEnabled(False)
        self.btn_start_check.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.btn_start_check.setObjectName("btn_start_check")
        self.horizontalLayout_2.addWidget(self.btn_start_check)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 539, 591, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_start_rec = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_start_rec.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.btn_start_rec.setObjectName("btn_start_rec")
        self.horizontalLayout_6.addWidget(self.btn_start_rec)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox.setEnabled(True)
        self.spinBox.setStyleSheet("color: rgb(0, 0, 0);")
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_4.addWidget(self.spinBox)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lcd_rec = QtWidgets.QLCDNumber(self.layoutWidget1)
        self.lcd_rec.setObjectName("lcd_rec")
        self.horizontalLayout_3.addWidget(self.lcd_rec)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.btn_rec_current = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_rec_current.setEnabled(False)
        self.btn_rec_current.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.btn_rec_current.setObjectName("btn_rec_current")
        self.horizontalLayout_5.addWidget(self.btn_rec_current)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.btn_Init_mysql, self.checkBox_external)
        Form.setTabOrder(self.checkBox_external, self.btn_open_camera)
        Form.setTabOrder(self.btn_open_camera, self.btn_start_check)
        Form.setTabOrder(self.btn_start_check, self.btn_start_rec)
        Form.setTabOrder(self.btn_start_rec, self.btn_rec_current)
        Form.setTabOrder(self.btn_rec_current, self.textEdit)
        Form.setTabOrder(self.textEdit, self.btn_sync_mysql)
        Form.setTabOrder(self.btn_sync_mysql, self.tableWidget)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox_2.setTitle(_translate("Form", "数据录入"))
        self.groupBox_3.setTitle(_translate("Form", "数据库状态"))
        self.btn_Init_mysql.setText(_translate("Form", "初始化数据库"))
        self.label_3.setText(_translate("Form", "数据库已存数据样本数："))
        self.groupBox_4.setTitle(_translate("Form", "信息显示"))
        self.btn_sync_mysql.setText(_translate("Form", "同步到数据库"))
        self.groupBox_5.setTitle(_translate("Form", "实时日志"))
        self.groupBox.setTitle(_translate("Form", "人脸采集"))
        self.face_label.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">摄像头未开启</span></p></body></html>"))
        self.checkBox_external.setText(_translate("Form", "使用外接摄像头"))
        self.btn_open_camera.setText(_translate("Form", "打开摄像头"))
        self.btn_start_check.setText(_translate("Form", "开启人脸检测"))
        self.btn_start_rec.setText(_translate("Form", "开始采集数据"))
        self.label.setText(_translate("Form", "设置捕获帧数："))
        self.label_2.setText(_translate("Form", "已采集帧数："))
        self.btn_rec_current.setText(_translate("Form", "采集当前捕获帧"))
import aaa_rc
