# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceTrain.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(836, 599)
        Form.setMinimumSize(QtCore.QSize(836, 599))
        Form.setMaximumSize(QtCore.QSize(836, 599))
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 841, 601))
        self.frame.setStyleSheet("QFrame {\n"
"border-image:url(:/lay/image/login1.png);\n"
"}\n"
"QLabel {\n"
"border-image:url();\n"
"}\n"
"QPushButton {\n"
"border-image:url();\n"
"}\n"
"QCheckBox {\n"
"border-image:url();\n"
"}\n"
"QTextEdit  {\n"
"border-image:url();\n"
"}\n"
"QLCDNumber  {\n"
"border-image:url();\n"
"}\n"
"QTableWidget  {\n"
"border-image:url();\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(550, 10, 271, 581))
        self.groupBox_2.setStyleSheet("color: rgb(207, 207, 207);")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 30, 251, 111))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 231, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_init_mysql = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_init_mysql.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.btn_init_mysql.setObjectName("btn_init_mysql")
        self.verticalLayout.addWidget(self.btn_init_mysql)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lcd_save = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcd_save.setObjectName("lcd_save")
        self.horizontalLayout.addWidget(self.lcd_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 150, 251, 91))
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.btn_train = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_train.setEnabled(False)
        self.btn_train.setGeometry(QtCore.QRect(10, 50, 231, 28))
        self.btn_train.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.btn_train.setObjectName("btn_train")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 260, 251, 311))
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_7)
        self.textEdit.setGeometry(QtCore.QRect(0, 20, 251, 291))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255,60);\n"
"color: rgb(0, 0, 0);")
        self.textEdit.setObjectName("textEdit")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 541, 581))
        self.groupBox.setStyleSheet("color: rgb(207, 207, 207);")
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 521, 261))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidget_pes = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_pes.setGeometry(QtCore.QRect(0, 20, 521, 241))
        self.tableWidget_pes.setStyleSheet("background-color: rgb(255, 255, 255,60);\n"
"color: rgb(0, 0, 0);")
        self.tableWidget_pes.setObjectName("tableWidget_pes")
        self.tableWidget_pes.setColumnCount(0)
        self.tableWidget_pes.setRowCount(0)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 290, 521, 261))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableWidget_ad = QtWidgets.QTableWidget(self.groupBox_4)
        self.tableWidget_ad.setGeometry(QtCore.QRect(0, 20, 521, 241))
        self.tableWidget_ad.setStyleSheet("background-color: rgb(255, 255, 255,60);\n"
"color: rgb(0, 0, 0);")
        self.tableWidget_ad.setObjectName("tableWidget_ad")
        self.tableWidget_ad.setColumnCount(0)
        self.tableWidget_ad.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(100, 560, 431, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tableWidget_pes, self.tableWidget_ad)
        Form.setTabOrder(self.tableWidget_ad, self.btn_init_mysql)
        Form.setTabOrder(self.btn_init_mysql, self.btn_train)
        Form.setTabOrder(self.btn_train, self.textEdit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "数据管理"))
        self.groupBox_5.setTitle(_translate("Form", "数据库状态"))
        self.btn_init_mysql.setText(_translate("Form", "初始化数据库"))
        self.label.setText(_translate("Form", "数据库已存数据个数："))
        self.groupBox_6.setTitle(_translate("Form", "训练数据"))
        self.btn_train.setText(_translate("Form", "开始训练"))
        self.groupBox_7.setTitle(_translate("Form", "实时日志"))
        self.groupBox.setTitle(_translate("Form", "人脸库"))
        self.groupBox_3.setTitle(_translate("Form", "员工人脸库"))
        self.groupBox_4.setTitle(_translate("Form", "管理员人脸库"))
        self.label_2.setText(_translate("Form", "注：Face ID为 -1 说明该用户的人脸数据未采集，0为未被训练"))
import aaa_rc
