# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FaceRecognition.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(836, 599)
        Form.setMinimumSize(QtCore.QSize(836, 599))
        Form.setMaximumSize(QtCore.QSize(836, 599))
        Form.setStyleSheet("")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 831, 601))
        self.frame.setStyleSheet("QFrame {\n"
"border-image:url(:/lay/image/login1.png);\n"
"}\n"
"QLabel {\n"
"border-image:url();\n"
"}\n"
"QPushButton {\n"
"border-image:url();\n"
"}\n"
"QCheckBox {\n"
"border-image:url();\n"
"}\n"
"QTextEdit  {\n"
"border-image:url();\n"
"}\n"
"QLCDNumber  {\n"
"border-image:url();\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(220, 10, 611, 581))
        self.groupBox.setAccessibleDescription("")
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setStyleSheet("color: rgb(207, 207, 207);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.face_label = QtWidgets.QLabel(self.groupBox)
        self.face_label.setGeometry(QtCore.QRect(10, 30, 591, 491))
        self.face_label.setStyleSheet("\n"
"border:1px solid black\n"
"")
        self.face_label.setObjectName("face_label")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(120, 529, 401, 31))
        font = QtGui.QFont()
        font.setFamily("华文彩云")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 201, 581))
        self.groupBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("color: rgb(207, 207, 207);")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 181, 131))
        self.groupBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_Init_mysql = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_Init_mysql.setGeometry(QtCore.QRect(10, 90, 161, 28))
        self.btn_Init_mysql.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);")
        self.btn_Init_mysql.setObjectName("btn_Init_mysql")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 161, 16))
        self.label_3.setObjectName("label_3")
        self.lcd_save = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcd_save.setGeometry(QtCore.QRect(40, 50, 101, 31))
        self.lcd_save.setObjectName("lcd_save")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 250, 181, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 161, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_track = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_track.setChecked(True)
        self.checkBox_track.setObjectName("checkBox_track")
        self.verticalLayout_2.addWidget(self.checkBox_track)
        self.checkBox_face_recognition = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_face_recognition.setEnabled(False)
        self.checkBox_face_recognition.setObjectName("checkBox_face_recognition")
        self.verticalLayout_2.addWidget(self.checkBox_face_recognition)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(9, 349, 181, 221))
        self.groupBox_5.setObjectName("groupBox_5")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit.setGeometry(QtCore.QRect(0, 20, 181, 201))
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255,60);\n"
"color: rgb(0, 0, 0);")
        self.textEdit.setObjectName("textEdit")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 160, 181, 81))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget1.setGeometry(QtCore.QRect(13, 20, 161, 56))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_external = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_external.setObjectName("checkBox_external")
        self.verticalLayout.addWidget(self.checkBox_external)
        self.btn_open_camera = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_open_camera.setStyleSheet("background-color: rgb(85, 170, 255,200);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.btn_open_camera.setObjectName("btn_open_camera")
        self.verticalLayout.addWidget(self.btn_open_camera)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.btn_Init_mysql, self.checkBox_external)
        Form.setTabOrder(self.checkBox_external, self.btn_open_camera)
        Form.setTabOrder(self.btn_open_camera, self.checkBox_track)
        Form.setTabOrder(self.checkBox_track, self.checkBox_face_recognition)
        Form.setTabOrder(self.checkBox_face_recognition, self.textEdit)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "摄像头实时数据"))
        self.face_label.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">摄像头未开启</span></p></body></html>"))
        self.label.setText(_translate("Form", "基于OpenCV的实时人脸识别"))
        self.groupBox_2.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox_2.setTitle(_translate("Form", "数据录入"))
        self.groupBox_3.setTitle(_translate("Form", "数据库状态"))
        self.btn_Init_mysql.setText(_translate("Form", "初始化数据库"))
        self.label_3.setText(_translate("Form", "数据库已存数据样本数："))
        self.groupBox_4.setTitle(_translate("Form", "功能开关"))
        self.checkBox_track.setText(_translate("Form", "人脸跟踪"))
        self.checkBox_face_recognition.setText(_translate("Form", "人脸识别"))
        self.groupBox_5.setTitle(_translate("Form", "实时日志"))
        self.groupBox_6.setTitle(_translate("Form", "图像捕获"))
        self.checkBox_external.setText(_translate("Form", "使用外接摄像头"))
        self.btn_open_camera.setText(_translate("Form", "打开摄像头"))
import aaa_rc
