# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_train.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(524, 541)
        Form.setMinimumSize(QtCore.QSize(524, 541))
        Form.setMaximumSize(QtCore.QSize(524, 541))
        Form.setStyleSheet("")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 521, 541))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.btn_show = QtWidgets.QPushButton(self.groupBox)
        self.btn_show.setGeometry(QtCore.QRect(150, 510, 93, 28))
        self.btn_show.setStyleSheet("background-color: rgb(194, 170, 255,200);\n"
"")
        self.btn_show.setObjectName("btn_show")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(70, 30, 401, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.btn_train = QtWidgets.QPushButton(self.groupBox)
        self.btn_train.setGeometry(QtCore.QRect(260, 510, 93, 28))
        self.btn_train.setStyleSheet("background-color: rgb(194, 170, 255,200);\n"
"")
        self.btn_train.setObjectName("btn_train")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 501, 241))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.tableWidget_pes = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget_pes.setGeometry(QtCore.QRect(0, 20, 501, 211))
        self.tableWidget_pes.setStyleSheet("background-color: rgb(255, 255, 255,60);")
        self.tableWidget_pes.setObjectName("tableWidget_pes")
        self.tableWidget_pes.setColumnCount(0)
        self.tableWidget_pes.setRowCount(0)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 270, 501, 231))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableWidget_ad = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_ad.setGeometry(QtCore.QRect(0, 20, 501, 211))
        self.tableWidget_ad.setStyleSheet("background-color: rgb(255, 255, 255,60);")
        self.tableWidget_ad.setObjectName("tableWidget_ad")
        self.tableWidget_ad.setColumnCount(0)
        self.tableWidget_ad.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tableWidget_pes, self.tableWidget_ad)
        Form.setTabOrder(self.tableWidget_ad, self.btn_show)
        Form.setTabOrder(self.btn_show, self.btn_train)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "人脸训练"))
        self.btn_show.setText(_translate("Form", "展示"))
        self.btn_train.setText(_translate("Form", "训练"))
        self.groupBox_2.setTitle(_translate("Form", "员工信息"))
        self.groupBox_3.setTitle(_translate("Form", "管理员信息"))
