# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_rec.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(524, 541)
        Form.setMinimumSize(QtCore.QSize(524, 541))
        Form.setMaximumSize(QtCore.QSize(524, 541))
        Form.setStyleSheet("")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 521, 541))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"border:1px solid rgb(217, 217, 217);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.btn_check = QtWidgets.QPushButton(self.groupBox)
        self.btn_check.setGeometry(QtCore.QRect(150, 500, 93, 28))
        self.btn_check.setStyleSheet("background-color: rgb(194, 170, 255,200);\n"
"")
        self.btn_check.setObjectName("btn_check")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(70, 30, 401, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 70, 231, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_psid = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_psid.setObjectName("radioButton_psid")
        self.horizontalLayout.addWidget(self.radioButton_psid)
        self.radioButton_adid = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_adid.setObjectName("radioButton_adid")
        self.horizontalLayout.addWidget(self.radioButton_adid)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(10, 130, 501, 361))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255,60);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 100, 291, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255,120);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.btn_record = QtWidgets.QPushButton(self.groupBox)
        self.btn_record.setGeometry(QtCore.QRect(260, 500, 93, 28))
        self.btn_record.setStyleSheet("background-color: rgb(194, 170, 255,200);\n"
"")
        self.btn_record.setObjectName("btn_record")
        self.label.setBuddy(self.lineEdit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.radioButton_psid, self.radioButton_adid)
        Form.setTabOrder(self.radioButton_adid, self.lineEdit)
        Form.setTabOrder(self.lineEdit, self.tableWidget)
        Form.setTabOrder(self.tableWidget, self.btn_check)
        Form.setTabOrder(self.btn_check, self.btn_record)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "人脸采集"))
        self.btn_check.setText(_translate("Form", "查询"))
        self.label_11.setText(_translate("Form", "请选择采集对象查询方式并输入其工号或账号"))
        self.radioButton_psid.setText(_translate("Form", "工号查询"))
        self.radioButton_adid.setText(_translate("Form", "账号查询"))
        self.label.setText(_translate("Form", "工号/账号："))
        self.lineEdit.setPlaceholderText(_translate("Form", "请输入工号或账号"))
        self.btn_record.setText(_translate("Form", "采集"))
