# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_sys.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(836, 599)
        Form.setMinimumSize(QtCore.QSize(836, 599))
        Form.setMaximumSize(QtCore.QSize(836, 599))
        Form.setStyleSheet("")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 841, 601))
        self.frame_2.setStyleSheet("QFrame  {\n"
"    background-image: url(D:/Pycharm/Core/opencv_face/image/msw2.png);\n"
"}\n"
"QWidget  {\n"
"border-image:url();\n"
"}\n"
"QLabel {\n"
"border-image:url();\n"
"}\n"
"QPushButton {\n"
"border-image:url();\n"
"}\n"
"QLineEdit {\n"
"border-image:url();\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setGeometry(QtCore.QRect(10, 10, 818, 581))
        self.splitter.setStyleSheet("")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setMinimumSize(QtCore.QSize(131, 581))
        self.groupBox.setMaximumSize(QtCore.QSize(131, 581))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"border:1px solid rgb(217, 217, 217);\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 111, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_msge = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_msge.setStyleSheet("background-color: rgb(194, 170, 255,200);\n"
"")
        self.btn_msge.setObjectName("btn_msge")
        self.verticalLayout.addWidget(self.btn_msge)
        self.btn_id = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_id.setStyleSheet("background-color: rgb(194, 170, 255,200);\n"
"")
        self.btn_id.setObjectName("btn_id")
        self.verticalLayout.addWidget(self.btn_id)
        self.btn_face = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_face.setStyleSheet("background-color: rgb(194, 170, 255,200);\n"
"")
        self.btn_face.setObjectName("btn_face")
        self.verticalLayout.addWidget(self.btn_face)
        self.btn_close = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_close.setStyleSheet("background-color: rgb(194, 170, 255,200);\n"
"")
        self.btn_close.setObjectName("btn_close")
        self.verticalLayout.addWidget(self.btn_close)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setMinimumSize(QtCore.QSize(681, 581))
        self.groupBox_2.setMaximumSize(QtCore.QSize(681, 581))
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"border:1px solid rgb(217, 217, 217);\n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 30, 661, 541))
        self.widget.setStyleSheet("\n"
"QFrame  {\n"
"background-image: url();\n"
"}\n"
"QWidget  {\n"
"border-image:url();\n"
"\n"
"}\n"
"QLabel {\n"
"border-image:url();\n"
"}\n"
"QPushButton {\n"
"border-image:url();\n"
"}\n"
"QLineEdit {\n"
"border-image:url();\n"
"}")
        self.widget.setObjectName("widget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "菜单"))
        self.btn_msge.setText(_translate("Form", "员工信息管理"))
        self.btn_id.setText(_translate("Form", "账号管理"))
        self.btn_face.setText(_translate("Form", "人脸库管理"))
        self.btn_close.setText(_translate("Form", "退出系统"))
        self.groupBox_2.setTitle(_translate("Form", "窗口"))
import aaa_rc
